name: Build

on:
  release:
    types:
      - published

env:
  TARGET_IMAGE: ${{ vars.DOCKERHUB_LOGIN }}/${{ vars.DOCKERHUB_IMAGE }}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract tag name
        id: tag
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const tag = context.payload.release.tag_name;
            return tag.startsWith('v') ? tag.slice(1) : tag;

      - name: Build Docker image
        run: docker build -t ${{ env.TARGET_IMAGE }}:${{ steps.tag.outputs.result }} -t ${{ env.TARGET_IMAGE }}:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to the registry
        run: docker push -a ${{ env.TARGET_IMAGE }}
